name: Build FAP

on:
  pull_request:    
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Build
        uses: oleksiikutuzov/flipperzero-ufbt-action@v1
        with:
          path: application
