name: Build FAP

on: 
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        path: folder
        
    - name: Build
      uses: oleksiikutuzov/flipperzero-ufbt-action@ufbt_to_opt
        
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        path: folder
        
    - name: Build
      uses: oleksiikutuzov/flipperzero-ufbt-action@ufbt_to_opt
      with:
        lint_only: true
        path: folder
